version: '2'
services:
  test:
    image: 'dsp/shellinabox:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:4200'
    networks:
      internal:
        ipv4_address: 192.168.1.3
    cap_add:
      - NET_ADMIN
  ftp_server:
    image: 'dsp/ftp_server:latest'
    stdin_open: true
    tty: true
    networks:
      internal:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
networks:
  internal:
    ipam:
      config:
        - subnet: 192.168.1.1/24
