version: '2'
services:
  Perete:
    image: 'dsp/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '90:80'
    networks:
      sameretre:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
networks:
  sameretre:
    ipam:
      config:
        - subnet: 192.168.1.1/24
