version: '2'
services:
  telnet_server:
    image: 'dsp/telnet_server:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.1.3
    cap_add:
      - NET_ADMIN
  telnet_client:
    image: 'dsp/debian_bot:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
  entry_point:
    image: 'dsp/shellinabox:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:4200'
    networks:
      internal_network:
        ipv4_address: 192.168.1.4
    volumes:
      - '/Users/gaetanoperrone/dsp/giper/lab2/t/:/t'
    cap_add:
      - NET_ADMIN
networks:
  internal_network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
